### PR TITLE
Fix error messages for invalid signatures.

### LINKED ISSUE #233: garbled text in error message
making request to https://api.rekor.dev/api/v1/log/entries/retrieve

with body:

<details>
<summary>click to show</summary>
<pre>
{
    "entries": [
        {
            "apiVersion": "0.0.1",
            "kind": "rekord",
            "spec": {
                "data": {
                    "content": "eyJDcml0aWNhbCI6eyJJZGVudGl0eSI6eyJkb2NrZXItcmVmZXJlbmNlIjoiIn0sIkltYWdlIjp7IkRvY2tlci1tYW5pZmVzdC1kaWdlc3QiOiJzaGEyNTY6MmI3MjFiYjFjNDZlYTYxOGU5NzZiNzAxYTc5ZGU0NWMzNTEzZWM0MWFhMmY0Mzg2YWQ1YTc4YzFhMzZkMTY1OCJ9LCJUeXBlIjoiY29zaWduIGNvbnRhaW5ldiBzaWduYXR1cmUifSwiT3B0aW9uYWwiOnsiazEiOiJ2MSJ9fQ=="
                },
                "signature": {
                    "content": "MEQCIGV/WmeH9wdf0HYpnDbAgXZIQDDCTk30VU1vjAGaTIdxAiBvrfJ7vf0yv4mQB+GkX5N7Lx0BKkDWBmod0fF69m0rwg==",
                    "publicKey": {
                        "content":"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFUUFobFpjR0Z6M1REYXVXbmVQTDlwNHkxYVFOZApUYmxFQ1F2dElwY3dGTTJ2czh6Q01GYkFXWUdOakJBbDlSY2pCOXhVZ2k4dEZrejRuRGtUaXVSRmFBPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
                    },
                    "format":"x509"
                }
            }
        }
    ]
}
</pre>
</details>

getting response

```
{
  "code": 500,
  "message": "signature mismatch for 0D\u0002 eZg��\u0007_�v)�6��vH@0�NM�UMo�\u0001�L�q\u0002 o��{��2���\u0007��_�{/\u001d\u0001*@�\u0006j\u001d��z�m+�"
}
```

which seems less than desirable. intentional?

### PR DESCRIPTION
**Pull request by dlorenc**
The error was turning signature bytes into a string directly. We could
base64 encode it, but that's not terribly useful either.

Signed-off-by: Dan Lorenc <dlorenc@google.com>

Fixes #233

### CODE REVIEW

File: pkg/pki/x509/x509.go [hunk 1]
```diff
@@ -81,12 +82,12 @@ func (s Signature) Verify(r io.Reader, k interface{}) error {
...
 			return nil
 		}
-		return fmt.Errorf("signature mismatch for %s", string(s.signature))
+		return errors.New("supplied signature does not match key")
 	case *ecdsa.PublicKey:
 		if ecdsa.VerifyASN1(pub, hash, s.signature) {
 			return nil
 		}
-		return fmt.Errorf("signature mismatch for %s", string(s.signature))
+		rreturn errors.New("supplied signature does not match key")
```
Comment (lukehinds) [inline pkg/pki/x509/x509.go]: you have an extra 'r' on your return there

**Review by lukehinds — APPROVED** [review]
other then the nit, looks good!

File: pkg/pki/x509/x509.go (hunk 1 above)
Comment (dlorenc) [reply pkg/pki/x509/x509.go]: doh! fixed

**Review by lukehinds — APPROVED** [review]
