### PR TITLE
persist URL along with state for comparison

### LINKED ISSUE #142: incorrect CLI persisted log state error
There are scenarios for the CLI where the server queried may not be the same as where the log state information that persisted in the `~/.rekor/` directory was obtained from. If this is the case, the CLI prints an incorrect error state in comparing states.

### PR DESCRIPTION
**Pull request by bobcallaway**
Signed-off-by: Bob Callaway <bcallawa@redhat.com>

fixes #142 

Also squelches `Using config file: ...` message if the format requested != default

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice!

File: cmd/cli/app/state/state.go [hunk 1]
```diff
@@ -26,14 +26,24 @@ import (
 	"github.com/mitchellh/go-homedir"
 )
 
-func Dump(lr *types.LogRootV1) error {
+type persistedLogRoot struct {
```
Comment (dlorenc) [inline cmd/cli/app/state/state.go]: Would it make sense to make this a map of url -> logroot? instead? So that way we can track multiple at the same time?

**Review by lukehinds — APPROVED** [review]
good idea!

File: cmd/cli/app/state/state.go (hunk 1 above)
Comment (bobcallaway) [reply cmd/cli/app/state/state.go]: well if we're going to do that, should we do `map[url]map[treeSize]*types.LogRootV1` so we can save not just the latest queried state from that server?

Comment (dlorenc) [reply cmd/cli/app/state/state.go]: IMO we probably don't want to store the entire tree state locally for every user - but we do need some way to do that for people that want to run full mirrors.

**Review by dlorenc — APPROVED** [review]
