### PR TITLE
Fix bug where /retrieve endpoint returns wrong logIndex across shards

### LINKED ISSUE #900: api/v1/log/entries/retrieve returns incorrect virtual log index for entries in the inactive shard
Repros in staging. e.g. retrieving logIndex 0 succeeds but returns virtual logIndex of 461. The rest of the entry is correct.

```
$ curl -s -H "Content-Type: application/json" --data '{"logIndexes": [0]}'  "https://rekor.sigstage.dev/api/v1/log/entries/retrieve"  | jq
[
  {
    "a0852d90cf669100ea7c0ef97fe870928dd43e8ab9e9986b95d0b4c8ef7e99a9": {
      "body": "eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI2NDRjMzZkODA4N2Y1MGRkZjRlN2I2N2ViNDlmZGI2NjY3N2ZjMWRkNjA4NGIyMmRlNjE2OGYxMWY5OTQ2ZjY1In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FVUNJUUMwWFdnMlVnZzQxZXNlVkswa3lTYnBOZnYrSmZvSm5nZTNCdjl5a3dsbjR3SWdlM2lOcUpUZ2FOYUxMUmFDVEQyVWJCenh4bmUvNHhkRUpTeWMwdUVoVGxJPSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTkZha05EUVZwbFowRjNTVUpCWjBsVVZEQk1VMGh4T1VsMU1sQnVlRmhQZDNWQ1prdGFaR2N6VVZSQlMwSm5aM0ZvYTJwUFVGRlJSRUY2UVhFS1RWSlZkMFYzV1VSV1VWRkxSWGQ0ZW1GWFpIcGtSemw1V2xNMWExcFlXWGhGVkVGUVFtZE9Wa0pCVFZSRFNFNXdXak5PTUdJelNteE5RalJZUkZSSmVRcE5SRkY1VFVSRk0wMXFUWGROTVc5WVJGUkplVTFFVVhsTlJFVXpUWHBOZDAxc2IzZEJSRUphVFVKTlIwSjVjVWRUVFRRNVFXZEZSME5EY1VkVFRUUTVDa0YzUlVoQk1FbEJRa0ZwV1ZSM01YWm5OMDFxTkdoM1JWbFplbTlUZFN0Nk1HZFdRbmx0WWt4Uk4zUkNkeXRyYTNnMllVSnhiREY1TnlzM1RXOXFla2dLZFhOT01HeFpURUZITDBwM1VsbFBkREJCZUVWQk5qRnpPV1ZsV201cEsycG5ZMVYzWjJOSmQwUm5XVVJXVWpCUVFWRklMMEpCVVVSQloyVkJUVUpOUndwQk1WVmtTbEZSVFUxQmIwZERRM05IUVZGVlJrSjNUVVJOUVhkSFFURlZaRVYzUlVJdmQxRkRUVUZCZDBoUldVUldVakJQUWtKWlJVWlFWWGRHTlRSa0NsbE5lRTlaUkhVMWFuUkVkRGhSSzBSVGVWVTVUVUk0UjBFeFZXUkpkMUZaVFVKaFFVWkdha0ZJYkN0U1VtRldiWEZZY2sxclMwZFVTWFJCY1hoaldEWUtUVU5KUjBFeFZXUkZVVVZDTDNkUldVMUNZVUpHU0VKNVlWaHNhRkZIVG05WlYyeDFXak5XYUdOdFVYVmFSMVl5VFVOclIwTnBjMGRCVVZGQ1p6YzRkd3BCVVVWRlJ6Sm9NR1JJUW5wUGFUaDJXVmRPYW1JelZuVmtTRTExV2pJNWRsb3llR3hNYlU1MllsUkJTMEpuWjNGb2EycFBVRkZSUkVGM1RuQkJSRUp0Q2tGcVJVRXlXRFZ4U0hwU1JqRXlPRFpUVTNsRUswcHlTWFUwV21GbmQwVndiV2RuWm1ZeVVERm5kaTlXYzJSMFkwZHVZMjlXTVZWNWJXNURUbkpsZHprS1NVVlZZa0ZxUlVGdk4ySTNSRVF2ZEVGUWJXaG5hbEJWV25oNlpsRnVSVEZtYVhvNU0yWjRlVU4wZWpSekx6SkJWM1JxVDJoRFpVcFhlamhPY1hSeE53cHdZMFpwSzJseFRnb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0ifX19fQ==",
      "integratedTime": 1650475384,
      "logID": "d32f30a3c32d639c2b762205a21c7bb07788e68283a4ae6f42118723a1bea496",
      "logIndex": 461,
      "verification": {
        "inclusionProof": {
          "hashes": [
            "95ef689564909df9ef12e1ca8dfca46a1a65ae177c8f103eb5762530e49c0354",
            "b2f912764447491ea3d0f82f662ee61dd0dbf76a46c4f06cb499744fd52d8ae8",
            "25475fd4aa5387723b82a27756b546d595d0b864d8567e02f1a15ffc56060da6",
            "7eb1942abaa808a0108706b07157b3a9cebe499c354f34f5023a8ff655528599",
            "b258f70cd31d1cbf7836c0cad04e4fc9cb713f1dc8a4d9b7ed9dd551992c941b",
            "25fbb7c22ba63d8445d75c9416c2368e4589f728cfabbbd23cd2b8bffec9a6b5",
            "22c06791403c0ccd7d20e406772596f2e753fb1cb54e869471a4848acfe8f603",
            "0d844aba73b8b6bf76d9c275bce861bf0e0e1edd216f04f5753f49b73865889c",
            "b6b49977d5a14b7d3ff1edb404b7516f316a97a8ed5b3ec4f1bacafea4a0fa76"
          ],
          "logIndex": 0,
          "rootHash": "ed4cb79f98642c7cd7626f8307d8fee48e04991dc4e827611884f131e53221ba",
          "treeSize": 461
        },
        "signedEntryTimestamp": "MEUCIA7IlU5iFY5uQskvewoI6FYgZMU3kngb9YMZrbBaTVy7AiEAghKSnMPGWWZB4SBq4TYRRI16RA5MDV9/tm7BGW03n0s="
      }
    }
  }
]
```

Getting the entry by logIndex directly returns the correct virtual logIndex:

```
$ curl -s -H "Accept: application/json" "https://rekor.sigstage.dev/api/v1/log/entries?logIndex=0" | jq -r
{
  "a0852d90cf669100ea7c0ef97fe870928dd43e8ab9e9986b95d0b4c8ef7e99a9": {
    "body": "eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI2NDRjMzZkODA4N2Y1MGRkZjRlN2I2N2ViNDlmZGI2NjY3N2ZjMWRkNjA4NGIyMmRlNjE2OGYxMWY5OTQ2ZjY1In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FVUNJUUMwWFdnMlVnZzQxZXNlVkswa3lTYnBOZnYrSmZvSm5nZTNCdjl5a3dsbjR3SWdlM2lOcUpUZ2FOYUxMUmFDVEQyVWJCenh4bmUvNHhkRUpTeWMwdUVoVGxJPSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTkZha05EUVZwbFowRjNTVUpCWjBsVVZEQk1VMGh4T1VsMU1sQnVlRmhQZDNWQ1prdGFaR2N6VVZSQlMwSm5aM0ZvYTJwUFVGRlJSRUY2UVhFS1RWSlZkMFYzV1VSV1VWRkxSWGQ0ZW1GWFpIcGtSemw1V2xNMWExcFlXWGhGVkVGUVFtZE9Wa0pCVFZSRFNFNXdXak5PTUdJelNteE5RalJZUkZSSmVRcE5SRkY1VFVSRk0wMXFUWGROTVc5WVJGUkplVTFFVVhsTlJFVXpUWHBOZDAxc2IzZEJSRUphVFVKTlIwSjVjVWRUVFRRNVFXZEZSME5EY1VkVFRUUTVDa0YzUlVoQk1FbEJRa0ZwV1ZSM01YWm5OMDFxTkdoM1JWbFplbTlUZFN0Nk1HZFdRbmx0WWt4Uk4zUkNkeXRyYTNnMllVSnhiREY1TnlzM1RXOXFla2dLZFhOT01HeFpURUZITDBwM1VsbFBkREJCZUVWQk5qRnpPV1ZsV201cEsycG5ZMVYzWjJOSmQwUm5XVVJXVWpCUVFWRklMMEpCVVVSQloyVkJUVUpOUndwQk1WVmtTbEZSVFUxQmIwZERRM05IUVZGVlJrSjNUVVJOUVhkSFFURlZaRVYzUlVJdmQxRkRUVUZCZDBoUldVUldVakJQUWtKWlJVWlFWWGRHTlRSa0NsbE5lRTlaUkhVMWFuUkVkRGhSSzBSVGVWVTVUVUk0UjBFeFZXUkpkMUZaVFVKaFFVWkdha0ZJYkN0U1VtRldiWEZZY2sxclMwZFVTWFJCY1hoaldEWUtUVU5KUjBFeFZXUkZVVVZDTDNkUldVMUNZVUpHU0VKNVlWaHNhRkZIVG05WlYyeDFXak5XYUdOdFVYVmFSMVl5VFVOclIwTnBjMGRCVVZGQ1p6YzRkd3BCVVVWRlJ6Sm9NR1JJUW5wUGFUaDJXVmRPYW1JelZuVmtTRTExV2pJNWRsb3llR3hNYlU1MllsUkJTMEpuWjNGb2EycFBVRkZSUkVGM1RuQkJSRUp0Q2tGcVJVRXlXRFZ4U0hwU1JqRXlPRFpUVTNsRUswcHlTWFUwV21GbmQwVndiV2RuWm1ZeVVERm5kaTlXYzJSMFkwZHVZMjlXTVZWNWJXNURUbkpsZHprS1NVVlZZa0ZxUlVGdk4ySTNSRVF2ZEVGUWJXaG5hbEJWV25oNlpsRnVSVEZtYVhvNU0yWjRlVU4wZWpSekx6SkJWM1JxVDJoRFpVcFhlamhPY1hSeE53cHdZMFpwSzJseFRnb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0ifX19fQ==",
    "integratedTime": 1650475384,
    "logID": "d32f30a3c32d639c2b762205a21c7bb07788e68283a4ae6f42118723a1bea496",
    "logIndex": 0,
    "verification": {
      "inclusionProof": {
        "hashes": [
          "95ef689564909df9ef12e1ca8dfca46a1a65ae177c8f103eb5762530e49c0354",
          "b2f912764447491ea3d0f82f662ee61dd0dbf76a46c4f06cb499744fd52d8ae8",
          "25475fd4aa5387723b82a27756b546d595d0b864d8567e02f1a15ffc56060da6",
          "7eb1942abaa808a0108706b07157b3a9cebe499c354f34f5023a8ff655528599",
          "b258f70cd31d1cbf7836c0cad04e4fc9cb713f1dc8a4d9b7ed9dd551992c941b",
          "25fbb7c22ba63d8445d75c9416c2368e4589f728cfabbbd23cd2b8bffec9a6b5",
          "22c06791403c0ccd7d20e406772596f2e753fb1cb54e869471a4848acfe8f603",
          "0d844aba73b8b6bf76d9c275bce861bf0e0e1edd216f04f5753f49b73865889c",
          "b6b49977d5a14b7d3ff1edb404b7516f316a97a8ed5b3ec4f1bacafea4a0fa76"
        ],
        "logIndex": 0,
        "rootHash": "ed4cb79f98642c7cd7626f8307d8fee48e04991dc4e827611884f131e53221ba",
        "treeSize": 461
      },
      "signedEntryTimestamp": "MEQCIG88jeKqFv2Fu/bH0SUF5W501M6xVEQZ1N3OL0tWtPS0AiAsmGKLPQQm0QJZboQbG/Q4Pu9049Q4qblMqcLeSeeTzA=="
    }
  }
}
```

Probably a trivial miscalculation introduced by the fix for https://github.com/sigstore/rekor/issues/892.

cc @priyawadhwa

### PR DESCRIPTION
**Pull request by priyawadhwa**
This was working for `get` but not `retrieve` -- updated the code so that they both rely on the same function. This should guarantee the same behavior from both endpoints and make things easier to maintain.

fixes https://github.com/sigstore/rekor/issues/900

Signed-off-by: Priya Wadhwa <priya@chainguard.dev>

### CODE REVIEW

File: pkg/api/entries.go [hunk 1]
```diff
@@ -411,46 +394,51 @@ func SearchLogQueryHandler(params entries.SearchLogQueryParams) middleware.Respo
...
+	tc := NewTrillianClientFromTreeID(ctx, tid)
+	log.ContextLogger(ctx).Debugf("Retrieving resolved index %v from TreeID %v", resolvedIndex, tid)
+
+	resp := tc.getLeafAndProofByIndex(resolvedIndex)
+	switch resp.status {
+	case codes.OK:
+	case codes.NotFound, codes.OutOfRange, codes.InvalidArgument:
+		return models.LogEntry{}, ErrNotFound
+	default:
+		return models.LogEntry{}, fmt.Errorf("%s: %w", trillianCommunicationError, resp.err)
```
Comment (asraa) [inline pkg/api/entries.go]: should this be a wrapped grpc error for `resp.err` and use the `handleRekorAPIError`?
```
		return handleRekorAPIError(params, http.StatusInternalServerError, fmt.Errorf("grpc err: %w", resp.err), trillianCommunicationError)
```

Comment (priyawadhwa) [reply pkg/api/entries.go]: WDYT of:


```go
return models.LogEntry{}, fmt.Errorf("grpc err: %w: %s", resp.err, trillianCommunicationError)
```

Since this is a helper function I'd prefer to avoid using `handleRekorAPIError`. I think this should contain all the same info in the error message and return the same status code.

Comment (asraa) [reply pkg/api/entries.go]: Ah! Good point, yeah! I see -- that works :P

Comment (priyawadhwa) [reply pkg/api/entries.go]: updated 😄

**Review by dlorenc — APPROVED** [review]

**Review by asraa — APPROVED** [review]
